FROM ghcr.io/serenity-js/playwright:v1.56.1-noble

# Copy welcome message for Codespaces/Dev Containers
COPY welcome-message.txt /usr/local/etc/vscode-dev-containers/first-run-notice.txt

WORKDIR /workspaces
